### ISSUE TITLE
Monthly summary-row bug?

### ISSUE THREAD

**Issue by Ubiux** [ClimenteA/PFASimplu#18]
![image](https://github.com/user-attachments/assets/eb906b08-4778-44cd-8c36-d8f61facedff)

Cred ca ceva nu merge cum trebuie legat de liniile care rezuma o anumita luna. Linia cu octombrie cred ca trebuia sa fie o linie mai jos, iar linia-rezumat pentru septembrie nu apare deloc.

**Comment by ClimenteA** [comment]
Mersi de info! 

Asa este linia cu calcul total trebuie sa fie la sfarsitul lunii. Voi veni cu un fix zilele astea.

**Comment by ClimenteA** [comment]
Incearca versiunea noua din releases

din versiunea pe care o ai acum:
- setari export -> stocare.zip va fi in descarcari

versiunea noua din releases unzip stocare.zip langa executabil 
din setari - import date din v2
