### ISSUE TITLE
Nu se importa facturile

### ISSUE THREAD

**Issue by Ubiux** [ClimenteA/PFASimplu#19]
Dupa ce s-a rezolvat #18 si am importat totul din vechea versiune, pare sa nu imi mai apara facturile, precum si autocomplete-ul cand incerc sa scriu una noua.

In cazul meu erau 2 facturi pe care le aveam pe vechea versiune, care nu apar deloc pe cea noua, dupa ce am importat.

**Comment by ClimenteA** [comment]
Ar fi trebuit export facturi in primul release v2, dar nu mi-a scapat. Versiunea curenta nu face export la facturi, e cam greut. Ar putea fi un input text cu un path catre versiunea veche in loc de import/export.

Ma uit zilele urmatoare. Oricum la calcul se iau in considerare doar  incasari, cheltuieli.

**Comment by ClimenteA** [comment]
In versiunea noua vei putea face export/import facturi. Prima data cand vei deschide versiunea noua va trebui sa adaugi ultima factura trimisa (sa ramana fie disponibile serie factura). Din pacate, nu am avut timp sa-l fac compatibil cu versiunea veche.
