### ISSUE TITLE
Noi functionalitati si actualizari

### ISSUE THREAD

**Issue by ClimenteA** [ClimenteA/PFASimplu#9]
- [x] Mutat de pe GO pe Python (mai rapid de creat aplicatia si mai multi devs care ar putea contribui);
- [x] Datele mutate din fisiere intr-un sqlitedb (tool migrare);
- [x] Sunt unele cheltuieli deductibile care trebuie calculate la 50%/25% din valoarea totala (carburant, etc); 
- [x] Posibilitate customizare template facturi (en/fr/ro/etc/multi-valute etc);
- [ ] Trimitere facturi in SPV;
- [x] TVA Intracomunitar (de vazut ce trebuie schimbat);
- [ ] Completare automata declaratie unica (poate cu semnatura digitala se poate face asta acum);
- [x] Fisa mijloc fix export PDF;
- [ ] Rapoartele Z pentru cei detin casa de marcat;  
- [ ] Eliberare chitante;
- [x] Design nou;
- [ ] NIR documentatie;

**Comment by LordPraslea** [comment]
Hi m8,

Interesant proiect. Mai ales ca e pe golang. Ma unge la suflet
Parerea mea: L-as mentine pe go din diverse motive ce tin de devops deployment 1 fisier de instalat pe vps si gata. 

Ma uit peste 1 sapt pe desktop sa vad ce si cum cand pot compila si sa ma uit prin cod. Pe mobil e mai greu.

Legat de efactura am gasit un proiect ce ar putea fii integrat tot in go 
https://github.com/printesoi/e-factura-go


Niste idei Pt declaratiile unice se poate folosi soft-ul J anaf ce lucreaza pe Jav(r)a 
Stiu ca rula ok pe linux acum cativa ani (nu am mai testat intre timp). Validarea manuala pdf tot pe un windoze trebuie facuta(sau ai gasit metode de a deschide oare pdf-ul pe linux?) 

+1111 pt stocare date in Sqlite  cu wall mode. 
Daca faci cloud version poti folosi actor pattern (1 pfa = 1 sqlite db)  
Poti sa te uiti si la sqlar (sqlite archive) oarecum util de avut 1 fisier separat pt toate upload-urile 
Asta ca bonus :-) 

Spor si buna treaba!

**Comment by ClimenteA** [comment]
Salut,

Go e super pentru distribuire - binary si merge peste tot. Daca te uiti prin cod sa stii ca nu e de cea mai buna calitate :sweat_smile: (am facut aplicatia asta sa invat Go).

Am vazut proiectul cu e-factura in go (pe reddit), merge integrat si in aplicatia asta.

Pentru declaratii inca trebuie soft j (java) de la ANAF. Voi incerca sa vad daca pot folosi softj din Go, daca nu nici Kotlin nu suna rau. Incercasem mai demult ceva in kotlin si am scos pdf, dar fara sa fie semnat digital.

Sqlite rocks! Ma gandeam si eu la fel un sqlitedb per user (multitenant ar fi overkill).

Nu stiam de sqlar arata interesant.

Inca nu am apucat sa lucrez la noile functionalitati. Trebuie sa gasesc o carte buna de contabilitate.

Mersi!

**Comment by ClimenteA** [comment]
Noua versiune va fi pe Typescript, Hono js cu Bunjs pentru a putea face cross platfrom executables.

**Comment by ClimenteA** [comment]
Am adaugat cat s-a putut intr-o aplicatie desktop. Pentru celelalte functionalitati nu am cunostinte de contabilitate suficiente. Sunt functionalitati care ar merge doar pe un server (integrare e-factura cu anaf, prea multe dependinte de instalat pentru a face declaratii, etc.). 

Per total e ok. In afara de faptul ca e facut in Python si nu se pot genera executabile la fel de fain ca in Go/JS.
